In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import preprocessing
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
Iris = pd.read_table('../datafiles/iris/iris.data', sep=',')
Iris = Iris.dropna(how="all")

In [3]:
Iris.tail()

Sepal length  Sepal width  Petal length  Petal width         Species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [4]:
label_encoder = preprocessing.LabelEncoder()
species = label_encoder.fit_transform(list(Iris['Species']))
species_names = ['Setosa', 'Verginica', 'Versicolor']

In [5]:
x = list(zip(list(Iris['Petal width']), list(Iris['Petal length']), list(Iris['Sepal width']), list(Iris['Sepal length'])))
y = list(species)

In [6]:
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size=0.35)

In [7]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train, y_train)
acc = model.score(x_test, y_test)

In [8]:
predicted = model.predict(x_test)

In [9]:
for x in range(len(predicted)):
    print('Predicted:', species_names[predicted[x]], 'Actual:', species_names[y_test[x]])

Predicted: Verginica Actual: Verginica
Predicted: Versicolor Actual: Versicolor
Predicted: Verginica Actual: Verginica
Predicted: Setosa Actual: Setosa
Predicted: Versicolor Actual: Versicolor
Predicted: Versicolor Actual: Versicolor
Predicted: Setosa Actual: Setosa
Predicted: Setosa Actual: Setosa
Predicted: Setosa Actual: Setosa
Predicted: Verginica Actual: Verginica
Predicted: Verginica Actual: Verginica
Predicted: Setosa Actual: Setosa
Predicted: Setosa Actual: Setosa
Predicted: Verginica Actual: Verginica
Predicted: Setosa Actual: Setosa
Predicted: Setosa Actual: Setosa
Predicted: Verginica Actual: Verginica
Predicted: Setosa Actual: Setosa
Predicted: Versicolor Actual: Versicolor
Predicted: Verginica Actual: Verginica
Predicted: Verginica Actual: Verginica
Predicted: Verginica Actual: Verginica
Predicted: Verginica Actual: Verginica
Predicted: Setosa Actual: Setosa
Predicted: Verginica Actual: Verginica
Predicted: Verginica Actual: Verginica
Predicted: Verginica Actual: Verginica

In [10]:
print(classification_report(y_test, predicted))
print(confusion_matrix(y_test, predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.95      0.95      0.95        22
           2       0.93      0.93      0.93        14

    accuracy                           0.96        53
   macro avg       0.96      0.96      0.96        53
weighted avg       0.96      0.96      0.96        53

[[17  0  0]
 [ 0 21  1]
 [ 0  1 13]]
